#!/usr/bin/env ruby

require "foo_bar"

command = ARGV.count > 0 ? ARGV[0].chomp.strip : ''

if command == "help" || command == "--help" || command == "-h"
  puts FooBar.help
  return
end

puts FooBar.main
