#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "azd_support"

AzdSupport::LogAzd.tee_to_log!("postprovision")
AzdSupport::LifecycleRunner.run("postprovision") do |runner|
  runner.step("grant_roles_to_az_user") { AzdSupport::Provisioning::GrantRolesToAzUser.run }
end
