#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "foo_bar"

FooBar::LogAzd.tee_to_log!("postprovision")
FooBar::LifecycleRunner.run("postprovision") do |runner|
  runner.step("grant_roles_to_az_user") { FooBar::Provisioning::GrantRolesToAzUser.run }
end
