#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "foo_bar"

FooBar::LogAzd.tee_to_log!("predeploy")
FooBar::LifecycleRunner.run("predeploy") do |runner|
  runner.step("enable_storage_access") { FooBar::Deploy::EnableStorageAccess.run }
end
