#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "azd_support"

AzdSupport::LogAzd.tee_to_log!("predeploy")
AzdSupport::LifecycleRunner.run("predeploy") do |runner|
  runner.step("enable_storage_access") { AzdSupport::Deploy::EnableStorageAccess.run }
end
