#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "azd_support"

AzdSupport::LogAzd.tee_to_log!("preprovision")
AzdSupport::LifecycleRunner.run("preprovision") do |runner|
  runner.step("validate_local_environment") { AzdSupport::Validation::LocalEnvironment.run }
end
