#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))
require "foo_bar"

FooBar::LogAzd.tee_to_log!("preprovision")
FooBar::LifecycleRunner.run("preprovision") do |runner|
  runner.step("validate_local_environment") { FooBar::Validation::LocalEnvironment.run }
end
