name: Main CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build image
        run: docker build -t ci-template-build:latest .
